# -*- mode: apache -*-
ServerName mattarikon-schema.dev
<VirtualHost *:80>
    <FilesMatch \.php$>
	SetHandler application/x-httpd-php
    </FilesMatch>

    DirectoryIndex index.php index.html

    DocumentRoot /var/www/html

    Alias /icons "/var/www/html/icons"

    <Directory /var/www/html>
	Options FollowSymlinks Indexes
	AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    SetEnvIf Request_URI "^/icons/" dontlog
    SetEnvIf Request_URI ".*\.png$" dontlog
    CustomLog /var/log/apache2/access.log combined env=!dontlog
</VirtualHost>
